name: Build

permissions:
  "contents": "write"

on:
  push:
    branches:
      - main
      - dev
      - winforms
  pull_request:
  workflow_dispatch:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        dotnet-version: [ '10.0.x' ]

    steps:
      - uses: actions/checkout@v7
      - name: Setup .NET 10
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build ShowTimeAlwaysOnTop.slnx -c Release --no-restore
      - name: Compress (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          Compress-Archive -Path ./ShowTimeAlwaysOnTop/bin/Release/* -DestinationPath ./ShowTimeAlwaysOnTop-${{ matrix.os }}.zip
          ls .
        shell: pwsh
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: ShowTimeAlwaysOnTop-${{ matrix.os }}
          path: ShowTimeAlwaysOnTop-${{ matrix.os }}.zip
  create-release:
    needs: [build]
    runs-on: ubuntu-latest
    if: (github.event_name == 'push' && github.ref == 'refs/heads/winforms')
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0 # allows for tags access
      - uses: actions/download-artifact@v8
        name: Download artifact
        with:
          name: ShowTimeAlwaysOnTop-windows-latest
          path: release-artifacts/
      - name: Create release
        uses: ncipollo/release-action@v1.21.0
        with:
          replacesArtifacts: true
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: "release-artifacts/*"
          body: ${{ github.event.head_commit.message }}
          prerelease: true
          name: Nightly Release
          tag: nightly-build
      - name: Update nightly-build tag
        run: |
          git tag -f nightly-build
          git push -f origin nightly-build
